### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by renanaragao** [juareznasato/vuetify-money#13]
Erro in unit test with jest.

![image](https://user-images.githubusercontent.com/5919017/91785588-1bcd6700-ebdc-11ea-9d21-10eee183c049.png)

**Comment by juareznasato** [comment]
Hi!
is there, the directory vuetify-money, into node_modules?

**Comment by renanaragao** [comment]
Yes, when I run the application with npm start it works, only in the npm test it will not.

**Comment by renanaragao** [comment]
`  transformIgnorePatterns: [
    '<rootDir>/node_modules/(?!vee-validate/dist/rules|vuetify-money)',
  ],`

It worked
