### ISSUE TITLE
Property backgroundColor not working inside a dark layout

### ISSUE THREAD

**Issue by henriquetroiano** [juareznasato/vuetify-money#42]
Hi guys!
If we put the vuetify-money inside a dark layout, tghere was a class 'white' localized in .v-text-field>.v-input__control>.v-input__slot that makes the field always backgrounded white event if i put the dark propery.
I could remove with jQuery this class white, but i believe that is a bug.
![image](https://user-images.githubusercontent.com/63327237/145712678-2f3d0250-d5b8-4312-9ef7-1180904bfec1.png)
![image](https://user-images.githubusercontent.com/63327237/145712695-dc9f4db0-10a2-4cd8-8306-a1aca27b47d1.png)
![image](https://user-images.githubusercontent.com/63327237/145712711-6bd95988-b688-43af-b77c-16914b4db489.png)
![image](https://user-images.githubusercontent.com/63327237/145712732-e5c4dc2d-6b1b-4d5a-86a0-199ef5ca56c2.png)
as you can see, the dark property works correctly, but the backgroundColor not
![image](https://user-images.githubusercontent.com/63327237/145712795-046a080a-549a-43bb-a2c4-79f8d222ba68.png)

Environment Details:
![image](https://user-images.githubusercontent.com/63327237/145712836-2cf0b6ee-b000-4e7a-807d-bc7c94c51dab.png)
![image](https://user-images.githubusercontent.com/63327237/145712854-ccf6bd9c-5941-4111-9698-7202266f0d52.png)

Thanks in advance

**Comment by guigagb** [comment]
Try this: 
`
<vuetify-money
          label="Test"
          v-model="value"
          background-color="#151515"
        ></vuetify-money>
`

**Comment by henriquetroiano** [comment]
Yup, that worked, thanks!
